version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: crm_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-crm_admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-crm_pass}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-crm_db}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

volumes:
  mongo_data:

networks:
  app-net:
    external: true