services:
  crm-back-orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ${IMAGE_NAME}
    container_name: ${IMAGE_NAME}
    ports:
      - "${PORT}:${PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${VOLUME_LOCAL}:${VOLUME_INTERNAL}
    command: >
      sh -c "nodemon --watch package.json --watch yarn.lock --watch node_modules --exec 'nest start --watch'"
    networks:
      - app_sba_net
  redis_crm_back_orchestrator:
    image: ${REDIS_IMAGE}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${REDIS_DATA_DIR}:${REDIS_DATA_DIR_INTERNAL}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app_sba_net
    container_name: ${REDIS_CONTAINER_NAME}

networks:
  app_sba_net:
    name: ${APP_NETWORK}
    external: true